### ISSUE TITLE
Wrong convert bem

### ISSUE THREAD

**Issue by dimensi** [emmetio/html-transform#3]
`.ct-target>(.-wrapper-img>.-img+.-title)` expand to
```
<div class="ct-target">
    <div class="ct-target__wrapper">
      <div class="ct-target__img"></div>
      <div class="ct-target__title"></div>
    </div>
</div>
```

wrapper-img element converted into wrapper, word `img` dissapered.

**Comment by dimensi** [comment]
`.ct-target__bar` -> `<div class="ct-target ct-target__bar"></div>`
`.ct-target-bar` -> `<div class="ct-target-bar"></div>`
`ct-target_bar` -> `<div class="ct-target ct-target_bar"></div>`

how me transform into `<div class="ct-target__bar"></div>`

**Comment by ramya-rao-a** [comment]
cc @sergeche

**Comment by octref** [comment]
@sergeche Wondering if you can take a look.

**Comment by sergeche** [comment]
Will take a look a bit later, too much work right now, sorry

**Comment by ramya-rao-a** [comment]
@edDimensi The issue you have reported in https://github.com/emmetio/html-transform/issues/3#issue-257727834 was fixed a few months ago.

About your question in https://github.com/emmetio/html-transform/issues/3#issuecomment-329503952

`.ct-target>.-bar` will give you
```
<div class="ct-target">
    <div class="ct-target__bar"></div>
</div>
```

@sergeche I would suggest to close this issue

**Comment by sergeche** [comment]
Yes, seems to be fixed with latest BEM resolver updates

**Comment by dimensi** [comment]
@ramya-rao-a, @sergeche it's not fixed.
This `.test>.-test-my` transform into 
```
<div class="test">
        <div class="test__test"></div>
 </div>
```
But i expect 
```
<div class="test">
   <div class="test__test-my"></div>
</div>
```
I test it on vscode 1.19.2

**Comment by ramya-rao-a** [comment]
@edDimensi The fix is available in the VS Code Insiders which you can get from https://code.visualstudio.com/insiders. If you want to see it in the stable build you will have to wait for the 1.20 release which should be in about 2 weeks
